export { default as Profile } from './UserProfile.vue'
export { default as OAuth } from './OAuth.vue'
export { default as DiscourseTl3Requirements } from './DiscourseTl3Requirements.vue'
export { default as UpdatePassword } from './UpdatePassword.vue'
export { default as UpdateAccount } from './UpdateAccount.vue'